version: "3.8"

services:

  db:
    container_name: postgres_db
    image: postgres
    restart: always
    user: postgres
    expose:
      - 5432
    environment:
      POSTGRES_USERNAME: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: test_db
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d test_db" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    volumes:
      - .:/docker-entrypoint-initdb.d
#      - ./db_schemas/db.sql:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - mynet

  pgadmin:
    container_name: pgadmin4
    image: dpage/pgadmin4
    restart: always
    expose:
      - 5050
    depends_on:
      - db
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PG_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PG_PASS}
    ports:
      - ${PG_PORTS}
    networks:
      - mynet

networks:
  mynet:
    driver: bridge

volumes:
  db:
    driver: local